# This file was generated by GoReleaser. DO NOT EDIT.
cask "otata" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "dd8898c53999af0055ddb8c15fdc4e666d282bb4acd48f2ab8945b94b3d9d7a6"
      url "https://github.com/jonathan-lor/otata/releases/download/v#{version}/otata_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "50d8397a3a1eeefd485408c7e1d013cb770fa6b3228bd605082bb41eb5ff4ef6"
      url "https://github.com/jonathan-lor/otata/releases/download/v#{version}/otata_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "otata"
  desc "Over-the-air installer for iOS and Android builds on your own network"
  homepage "https://github.com/jonathan-lor/otata"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otata"

  uninstall launchctl: [
      "com.anakepha.otata",
    ]

  zap trash: [
      "~/Library/LaunchAgents/com.anakepha.otata.plist",
      "~/.otata",
    ]

end
