# This file was generated by GoReleaser. DO NOT EDIT.
cask "otata" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5cf9fad37ec1b985dc0e356e86fc917ab6501f495aa93162284c9b91a3cc49ce"
      url "https://github.com/jonathan-lor/otata/releases/download/v#{version}/otata_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8784101730b0113793ba0b1a5be67da3f1b5ea8d0c22da8469898bd42db8376"
      url "https://github.com/jonathan-lor/otata/releases/download/v#{version}/otata_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "otata"
  desc "Over-the-air installer for iOS builds on your own network"
  homepage "https://github.com/jonathan-lor/otata"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otata"

  uninstall launchctl: [
      "com.anakepha.otata",
    ]

  zap trash: [
      "~/Library/LaunchAgents/com.anakepha.otata.plist",
      "~/.otata",
    ]

end
