# This file was generated by GoReleaser. DO NOT EDIT.
cask "otata" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "3e4b606b891c9a6c2822056ef5e53b6693e889924fc9ea742165331814bb89fc"
      url "https://github.com/jonathan-lor/otata/releases/download/v#{version}/otata_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "10fc871b9977ee00323cfec57b043dfd4b4358694a5001c888387a3100499279"
      url "https://github.com/jonathan-lor/otata/releases/download/v#{version}/otata_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "otata"
  desc "Over-the-air installer for iOS and Android builds on your own network"
  homepage "https://github.com/jonathan-lor/otata"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otata"

  uninstall launchctl: [
      "com.anakepha.otata",
    ]

  zap trash: [
      "~/Library/LaunchAgents/com.anakepha.otata.plist",
      "~/.otata",
    ]

end
